@startuml
title 点歌 API 时序图
autonumber
skinparam monochrome true
participant "App" as a
participant "声网 SDK" as b
== 初始化 KTV API 模块==
a -> b: initWithRtcEngine
== 获取歌曲列表（方式一：用关键词）==
a -> b: loadSearchDataWithKeyWord
b -->> a: onMusicCollectionResult
== 获取歌曲列表（方式二：用音乐榜单）==
a -> b: loadDataWithIndex
b -->> a: onMusicChartsResult
== 加载歌曲 ==
a -> b: loadSong
== 开始播放歌曲 ==
b -->> a: KTVLoadSongStateOK
a -> b: playSong
b -->> a: didChangedToState(AgoraMediaPlayerStatePlaying)
== 控制歌曲播放 ==
a ->b: seek/pause/resume/selectTrackMode
b -->> a: didChangedToState(AgoraMediaPlayerStateXX)
== 停止播放 ==
a -> b: stopSong
b -->> a: didChangedToState(AgoraMediaPlayerStateStopped)
@enduml