@startuml
skinparam monochrome true
class AgoraBaseClassActivity
class AgoraEduClassActivity
class AgoraClass1V1Activity
class AgoraClassSmallActivity
class AgoraClassLargeActivity
AgoraBaseClassActivity <|-- AgoraEduClassActivity
AgoraEduClassActivity <|-- AgoraClassSmallActivity
AgoraEduClassActivity <|-- AgoraClassLargeActivity
AgoraEduClassActivity <|-- AgoraClass1V1Activity
note left: Activity for each classroom type
@enduml

