@startuml
autonumber
skinparam monochrome true
participant "RTC SDK" as rtc
participant "Android app" as app
participant "RTM SDK" as rtm
participant "云服务" as cloud
== 登录 RTM 系统 ==
app -> rtm: createInstance
app -> rtm: login
== 创建直播间 ==
app -> cloud: post create room
cloud -->> app: create room result
== 加入直播间 ==
app -> cloud: post join room
cloud -->> app: join room result
note right
返回直播间信息，包括用户
列表、用户信息、房间信息
end note
== 加入 RTC 和 RTM 频道并开始直播 ==
app -> rtc: create
app -> rtc: enableVideo
app -> rtc: setChannelProfile(BROADCASTING)
app -> rtc: setClientRole(BROADCASTER)
app -> rtc: setupLocalVideo
app -> rtc: joinChannel
rtc -->> app: onJoinChannelSuccess
app -> rtm: createChannel˚
app -> rtm: join
rtm -->> app: onSuccess
== 停止直播并离开 RTC 和 RTM 频道 ==
app -> cloud: post leave room
app -> rtm: leave
app -> rtm: logout
app -> rtc: leaveChannel
@enduml