group:
  # first group
  files:
      - source: .github/
        dest: .github/
      - source: scripts/
        dest: scripts/
      - source: xml2json/
        dest: xml2json/
      - source: .husky/
        dest: .husky/
  repos: |
      AgoraIO/agora_doc_source@release/rtc-ng/4.0.0
      AgoraIO/agora_doc_source@3.8.200-framework-suri 
      AgoraIO/agora_doc_source@release/rtc-ng/3.8.200-kelu
      AgoraIO/agora_doc_source@3.8.200-flutter
      AgoraIO/agora_doc_source@3.8.200-electron-yaxi
  # AgoraIO/doc_source@release/rtc-ng/3.8.200
  # AgoraIO/doc_source@release/rtc-ng/3.7.203-unity
  # AgoraIO/agora_doc_source@release/rtc-ng/3.8.200
  # AgoraIO/agora_doc_source@release/rtc-ng/3.7.203-unity
