group:
  # first group
  - files:
      - source: .github/
        dest: .github/
      - source: scripts/
        dest: scripts/
      - source: xml2json/
        dest: xml2json/
      - source: .husky/
        dest: .husky/
  repos: |
      Agoradoc/doc_source@release/rtc-ng/3.8.200
