group:
  # first group
  files:
      - source: .github/
        dest: .github/
      - source: scripts/
        dest: scripts/
      - source: xml2json/
        dest: xml2json/
      - source: .husky/
        dest: .husky/
  repos: |
      AgoraDoc/doc_source@release/rtc-ng/3.8.200
      AgoraDoc/doc_source@release/rtc-ng/3.7.203-unity
  # AgoraIO/doc_source@release/rtc-ng/3.8.200
  # AgoraIO/doc_source@release/rtc-ng/3.7.203-unity
