group:
  # first group
  files:
      - source: .github/
        dest: .github/
      - source: scripts/
        dest: scripts/
      - source: xml2json/
        dest: xml2json/
      - source: .husky/
        dest: .husky/
  repos: |
      AgoraIO/agora_doc_source@master           
      AgoraIO/agora_doc_source@release/rtc-ng/4.1.0           
      AgoraIO/agora_doc_source@release/flexible-classroom/2.7.0
  # AgoraIO/agora_doc_source@release/rtc-ng/4.0.0-framework
  # AgoraIO/doc_source@release/rtc-ng/3.8.200
  # AgoraIO/doc_source@release/rtc-ng/3.7.203-unity
  # AgoraIO/agora_doc_source@release/rtc-ng/3.8.200
  # AgoraIO/agora_doc_source@release/rtc-ng/3.7.203-unity
