@startuml
autonumber
skinparam monochrome true
participant "App" as a #White
participant "RtcEngine" as b
participant "ILocalSpatialAudioEngine" as c
participant "IMetachatScene" as d
participant "IMetachatSceneEventHandler" as e
app -> scene: enableVideoDisplay
== 播放视频文件 ==
app -> player: open
app -> player: play
observer --> app: onFrame
== 推视频帧 ==
app -> scene: pushVideoFrameToDisplay
@enduml