extends: capitalization
message: "'%s' should use sentence-style capitalization."
link: "https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings"
level: warning
scope: heading
match: $sentence
indicators:
    - ":"
exceptions:
    - Agora Analytics
    - Agora Cloud Recording
    - Agora Console
    - Agora Interactive Live Streaming Premium
    - Agora Interactive Live Streaming Standard
    - Agora Interactive Whiteboard
    - Agora MediaPlayer Kit
    - Agora On-premise Recording SDK
    - Agora Real-time Messaging
    - Agora RTM SDK
    - Agora SD-RTN
    - Agora Video Call
    - Agora Video SDK
    - Agora Voice Call
    - Agora Voice SDK
    - AI Interactive Classroom
    - Azure
    - Breakout Class
    - Lecture Hall
    - CLI
    - Code
    - Docker
    - I
    - Kubernetes
    - Linux
    - Live-stream Shopping
    - macOS
    - Marketplace
    - MongoDB
    - Multiple Hosts
    - One-to-one Classroom
    - PK Host
    - Small Classroom
    - Single Host
    - Studio
    - TypeScript
    - URLs
    - Virtual Host
    - Visual
    - VS
    - Windows
