extends: spelling
message: "Did you really mean '%s'?"
level: error
ignore:
    # Relative path to StylesPath
    - ignore.txt
# The default dictionary is https://github.com/errata-ai/en_US-web
# Comment out the following to use custom .dic files
# dicpath: ../../fixtures/spelling/dics
# dictionaries:
#  - en_US
