# 注释模板配置文件

# 基础注释模板
base_template: |
  /**
   * @brief {brief}
   * {technical_preview}
   * {preserved_since}
   * {preserved_deprecated}
   *
   * @details {details}
   *
   * @note {note}
   *
   * {parameters}
   *
   * @return {return}
   */

# Java特有模板（包含throws）
java_template: |
  /**
   * @brief {brief}
   * {technical_preview}
   * {preserved_since}
   * {preserved_deprecated}
   *
   * @details {details}
   *
   * @note {note}
   *
   * {parameters}
   *
   * @return {return}
   * @throws {throws}
   */

# 字段替换说明
field_descriptions:
  brief: "API简述"
  technical_preview: "技术预览标记"
  preserved_since: "保留的since信息"
  preserved_deprecated: "保留的deprecated信息"
  details: "详细描述"
  note: "注意事项"
  parameters: "参数说明"
  return: "返回值说明"
  throws: "抛出异常说明(Java)"
