@startuml
title 合唱 API 时序图
autonumber
skinparam monochrome true
participant "领唱/伴唱 App" as a
participant "声网 SDK" as b
participant "听众 App" as c
== 加入频道 ==
a -> b: joinChannel
c -> b: joinChannel
== 加载歌曲歌词并播放 ==
a -> b: loadMusic()
note left
autoPlay 设为 true，歌曲加载成功后自动播放
end note
b -->> a: onMusicLoadSuccess
note right
autoPlay 设为 false，仅加载歌词
听众不播放歌曲，只是进入播放状态
end note
c -> b: loadMusic()
b -->> c: onMusicLoadSuccess
== 切换角色 ==
a -> b:swithSingerRole(LeadSinger/CoSinger)
b --> a: onSingerRoleChanged
note left
伴唱加入合唱后，独唱者变为 LeadSinger
伴唱将角色设为 CoSinger
end note
== 歌曲结束 ==
a -> b: swithSingerRole(Audience)
b -->> a: onSingerRoleChanged
== 关闭麦克风 ==
a -> b: adjustRecordingSignalVolume
== 更新媒体选项 ==
a -> b: updateChannelMediaOptions
c -> b: updateChannelMediaOptions
note left
独唱、伴唱、上麦听众发布麦克风，角色为主播
普通听众不发布麦克风，角色为观众
end note
@enduml