
:rootdir: .
ifdef::doc_build[]
:include_dir: content/project_name
endif::[]
ifndef::doc_build[]
:include_dir: .
endif::[]

include::{include_dir}/.variables.adoc[]

////
The anchor tag is also the file name. The file name must be the same as the tag.
////
[#subject_context]
//The title describes what you will explain. For example: "SAP Hana Architecture".
= Why something works the way it does

Introduction paragraph that says what you are about to explain and why it will help the reader.



This section shows you how to...



== Prerequisites
// This section is optional, if you need to know absolutely nothing to understand the page, remove it.
In order to understand this page you need:

* Sound knowledge of \http://fascinating.stuff.ohyeah[Some very clever technical thing]
* Sound knowledge of \http://fascinating.stuff.ohyeah[Another very clever technical thing]


== Use sections for new topics

Sections make a visual distinction for a logical subject in your text. Keep you sections concise and too the point.

After an intro sentence, a picture tells a thousand words. Architecture diagram, sequence, screenshot. It helps.
After an intro sentence, a picture tells a thousand words. Architecture diagram, sequence, screenshot. It helps.



[mermaid, concept_template, svg]
----
include::{include_dir}/images/infrastructure_deployment.mmd[]
----

As you can see, use scripted diagrams as much as possible.



== Use subsections for new topics

An example of a second section reinforces the point written in the previous section.


Please, keep it short. An academic treatise is fun to write at university. Your readers want just enough information for them to work on a project. No more, no less.

