
:rootdir: .
ifdef::doc_build[]
:include_dir: content/project_name
endif::[]
ifndef::doc_build[]
:include_dir: .
endif::[]

include::{include_dir}/.variables.adoc[]

////
The anchor tag is also the file name. The file name must be the same as the tag.
////
[#subject_reference]
= <subject> reference

////
If you think it will help the user, add some contextual information here to explain the subject you are writing reference material for.

If the reference information is in more than one group,  use subheadings

==  A functional area

==  Another functional area

////

You use the following to configure or develop <subject>:

[%header,cols="1,1,1,6"]
|===
| Name | Default | Type | Description

| shakespeare
| playwright
| job

a| Set `shakespeare` to `poet` to enable the sonnet writing functionality for this instance.

Possible values are:

* `actor` - someone who pretends to be someone else while performing in a film, play, or television or radio programme.
* `director` - a person who is in charge of a film or play and tells the actors how to play their parts.
* `impresario` - a person who arranges different types of public entertainment, such as theatre, musical, and dance events.
* `playwright` - a person who writes https://en.wikipedia.org/wiki/Play_(theatre)[plays].
* `poet` - a person who writes https://en.wikipedia.org/wiki/Poetry[poems].

|===


