@startuml
autonumber
title 换装捏脸 Objective-C API 时序图
participant "App" as app #LightGrey
participant "AgoraRtcEngineKit" as rtc #White
participant "AgoraMetaServiceKit" as service
participant "AgoraMetaScene" as scene
participant "AgoraMetaLocalUserAvatar" as avatar
participant "AgoraMetaEventDelegate" as serviceevent
participant "AgoraMetaSceneEventDelegate" as sceneevent
== 创建并初始化 AgoraMetaServiceKit ==
app -> rtc: sharedEngineWithConfig
app -> service: sharedMetaServiceWithConfig
== 获取并下载场景资源 ==
app -> service: getSceneAssetsInfo
serviceevent -->> app: onGetSceneAssetsInfoResult
app -> service: downloadSceneAssets
serviceevent -->> app: onDownloadSceneAssetsProgress
== 创建 AgoraMetaScene ==
critical #LightYellow
app -> app: 解压 icon 资源压缩包并设置 UI
end
app -> service: createScene
service -> scene: new
scene -->> service: return
service -->> app: AgoraMetaScene
serviceevent -->> app: onCreateSceneResult
serviceevent -->> app: onConnectionStateChanged
== 设置用户信息并进入场景 ==
app -> scene: getLocalUserAvatar
app -> avatar: setUserInfo
app -> avatar: setModelInfo
app -> avatar: setExtraInfo
app -> scene: createRenderView
app -> scene: enterScene
sceneevent -->> app: onEnterSceneResult
== 换装和捏脸 ==
critical #LightYellow
app -> scene: sendSceneMessage(updateDress)
app -> scene: sendSceneMessage(updateFace)
end
== 离开场景并释放资源 ==
app -> scene: leaveScene
sceneevent -->> app: onLeaveSceneResult
app -> scene: release
sceneevent -->> app: onReleasedScene
app -> service: destroy
app -> rtc: destroy
@enduml
