@startuml
title 用户进出语聊房的流程图
start
: 进入语聊房列表;
: 初始化信令系统;
: 登录信令系统;
if (是否需要创建房间) then (Yes)
    : 创建房间;
else(No)
endif
:进入房间;
fork
    :初始化 RTC 引擎;
    :[RTC] 加入频道;
  fork again
    :[信令] 加入聊天室;
  endfork
:显示聊天消息和声音;
if (是否离开房间) then (Yes)
fork
:[RTC] 退出频道;
:销毁 RTC 引擎;
fork again
:[信令] 离开聊天室;
endfork
if (角色是否为房主) then (Yes)
:销毁房间;
else (No)
:离开房间;
endif
else (No)
endif
stop
@enduml