@startuml
title 听众向房主申请上麦的流程图
start
if (角色是否为房主) then (Yes)
    :房主收到听众的上麦申请;
    if (房主是否同意申请) then (Yes)
    :房主发送接受听众上麦申请的通知;
    :房主修改麦位信息以让听众上麦;
    else (No)
    :房主发送拒绝听众上麦申请的通知;
    stop
    endif
else(No)
    :听众向房主发起上麦申请;
    :房主接受后，听众收到自己上麦的消息;
    :[RTC] 更新当前用户角色为主播;
    :[RTC] 发布本地音频流;
endif
:更新麦位 UI 界面;
stop
@enduml