@startuml
autonumber
participant "房主" as a
participant "声网即时通讯（IM）SDK" as b #White
participant "听众" as c
a -> b: 发送上麦邀请
b --> c: 发送上麦邀请
c -> c: 弹出上麦邀请的弹窗
alt #LightCyan 拒绝
c -> b: 拒绝上麦邀请
else #White 接受
c -> b: 同意上麦邀请
end
b --> a: 设置聊天室属性，通知全员刷新房间设置
a -> a: 刷新 UI
b --> c: 设置聊天室属性，通知全员刷新房间设置
c -> c: 刷新 UI
@enduml