//
//  Agora Media SDK
//
//  Created by Zhuo Wang in 2021-09.
//  Copyright (c) 2021 Agora IO. All rights reserved.
//

namespace agora {
namespace rtc {

enum : int { INVLAID_VALUE = -1 };

struct VideoBeautyParam {
  enum {ID = 774};
  int version = INVLAID_VALUE;
  int smoothness = INVLAID_VALUE;
  int lightness = INVLAID_VALUE;
  int redness = INVLAID_VALUE;
  int contrast = INVLAID_VALUE;
  int sharpness = INVLAID_VALUE;
};

enum LocalExtensionCounter {
  LOCAL_EXTENSION_COUNTER_LOWLIGHT_ENHANCE_COST_TIME = 248,
  LOCAL_EXTENSION_COUNTER_BEAUTY_COST_TIME = 307,
  LOCAL_EXTENSION_COUNTER_PVC_COST_TIME = 308,
  LOCAL_EXTENSION_COUNTER_SEG_ENABLE = 658,
  LOCAL_EXTENSION_COUNTER_SEG_COST_TIME = 659,
  LOCAL_EXTENSION_COUNTER_BACKREPLACE_ENABLE = 660,
  LOCAL_EXTENSION_COUNTER_BACKREPLACE_COST_TIME = 661,
  LOCAL_EXTENSION_COUNTER_BLUR_COST_TIME = 768,
  LOCAL_EXTENSION_COUNTER_DENOISER_COST_TIME = 746,
  LOCAL_EXTENSION_COUNTER_COLOR_ENHANCE_COST_TIME = 747,
  LOCAL_EXTENSION_REMOTE_COUNTER_SUPER_RESOLUTION_TYPE =241,
  LOCAL_EXTENSION_REMOTE_COUNTER_SUPER_RESOLUTION_COST_TIME =242,
};

}  // namespace rtc
}  // namespace agora