@startuml
autonumber
title 融合场景 Objective-C API 时序图
participant "App" as app #LightGrey
participant "AgoraRtcEngineKit" as rtc #White
participant "AgoraMetaServiceKit" as service
participant "AgoraMetaScene" as scene
participant "AgoraMetaLocalUserAvatar" as avatar
participant "AgoraMetaEventDelegate" as serviceevent
participant "AgoraMetaSceneEventDelegate" as sceneevent
== 创建并初始化 AgoraMetaServiceKit ==
app -> rtc: sharedEngineWithConfig
app -> service: sharedMetaServiceWithConfig
== 获取并下载场景资源 ==
app -> service: getSceneAssetsInfo
serviceevent -->> app: onGetSceneAssetsInfoResult
app -> service: downloadSceneAssets
serviceevent -->> app: onDownloadSceneAssetsProgress
== 创建 AgoraMetaScene ==
app -> service: createScene
note right
config 中开启并设置面部捕捉插件
end note
service -> scene: new
scene -->> service: return
service -->> app: AgoraMetaScene
serviceevent -->> app: onCreateSceneResult
serviceevent -->> app: onConnectionStateChanged
== 设置用户信息并进入场景 ==
app -> scene: getLocalUserAvatar
app -> avatar: setUserInfo
app -> avatar: setModelInfo
app -> avatar: setExtraInfo
app -> scene: createRenderView
app -> scene: enterScene
sceneevent -->> app: onEnterSceneResult
== 加入频道并开启元直播 ==
app -> rtc: setupLocalVideo
app -> rtc: joinChannelByToken
app -> scene: addSceneView
sceneevent -->> app: onAddSceneViewResult
app -> scene: enableSceneVideoCapture(view,YES)
== 离开并释放资源 ==
app -> scene: removeSceneView
sceneevent -->> app: onRemoveSceneViewResult
app -> rtc: leaveChannel
app -> scene: leaveScene
sceneevent -->> app: onLeaveSceneResult
app -> scene: destroy
sceneevent -->> app: onReleasedScene
app -> service: destroy
app -> rtc: destroy
@enduml