# This workflow will use OxygenScript to build features.

name: Awesome OxygenScript for DITA style unification

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Unified XML file formatting
      run: |
          cd scripts/oxygen/scripts
          ./batchFormatAndIndent.sh -i ../../../dita -f *.dita -r -ih -v
          ./batchFormatAndIndent.sh -i ../../../en-US/dita -f *.dita -r -ih -v
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Format DITA files
          title: "[AUTO: MERGE AT YOUR EARLIEST CONVENIENCE] Format DITA files in a flash"
          branch: formatted-patch
          base: master
          reviewers: lemon-chen
          body: >
              This PR is auto-generated to format DITA files in a flash. @HeatherWYL  @Cilla-luodan
          labels: report, automated pr, formatting
          
