 # API注释更新工具主配置文件

# 代码仓库配置
repo_path: "./tests/src"

# HTML文档路径配置
html_sources:
  cpp-ng: "../../en-US/dita/out/cpp-ng/API"
  android-ng: "../../en-US/dita/out/android-ng/API"
  ios-ng: "../../en-US/dita/out/ios-ng/API"
  mac-ng: "../../en-US/dita/out/mac-ng/API"

# 各平台搜索路径配置（分离设计）
platforms:
  cpp-ng:
    include:
      - "*.h"
    exclude: []
  
  android-ng:
    include:
      - "*.java"
    exclude: []


  ios-ng:
    include:
      - "*.h"
    exclude: []    
  mac-ng:
    include:
      - "*.h"
    exclude: []
# 日志配置
logging:
  file_level: "debug"
  console_level: "debug"
  log_dir: "./logs"
  max_log_files: 30
